//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u23688794_HW03.Data
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using u23688794_HW03.Models;

    public partial class BikeStoresEntities : DbContext
    {
        public BikeStoresEntities()
            : base("name=BikeStoresEntities")
        {
        }

        public virtual DbSet<brands> brands { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<stocks> stocks { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<staffs> staffs { get; set; }
        public virtual DbSet<stores> stores { get; set; }

        /*  protected override void OnModelCreating(DbModelBuilder modelBuilder)
          {


              // Configure table names and schemas
              modelBuilder.Entity<staffs>().ToTable("staffs", "sales");
              modelBuilder.Entity<customers>().ToTable("customers", "sales");
              modelBuilder.Entity<products>().ToTable("products", "production");
              modelBuilder.Entity<brands>().ToTable("brands", "production");
              modelBuilder.Entity<categories>().ToTable("categories", "production");
              modelBuilder.Entity<stores>().ToTable("stores", "sales");
              modelBuilder.Entity<stocks>().ToTable("stocks", "production");
              modelBuilder.Entity<orders>().ToTable("orders", "sales");
              modelBuilder.Entity<order_items>().ToTable("order_items", "sales");


              // Staff -> Store relationship
              modelBuilder.Entity<staffs>()
                  .HasRequired(s => s.stores)
                  .WithMany()
                  .HasForeignKey(s => s.store_id);

              // Staff -> Manager (self-referencing) relationship
              modelBuilder.Entity<staffs>()
                  .HasOptional(s => s.staffs1)
                  .WithMany()
                  .HasForeignKey(s => s.manager_id);

              // Product -> Brand relationship
              modelBuilder.Entity<products>()
                  .HasRequired(p => p.brands)
                  .WithMany(b => b.products)
                  .HasForeignKey(p => p.brand_id);

              // Product -> Category relationship
              modelBuilder.Entity<products>()
                  .HasRequired(p => p.categories)
                  .WithMany(c => c.products)
                  .HasForeignKey(p => p.category_id);

              // Order -> Customer relationship
              modelBuilder.Entity<orders>()
                  .HasRequired(o => o.customers)
                  .WithMany(c => c.orders)
                  .HasForeignKey(o => o.customer_id);

              // Order -> Staff relationship
              modelBuilder.Entity<orders>()
                  .HasRequired(o => o.staffs)
                  .WithMany(s => s.orders)
                  .HasForeignKey(o => o.staff_id);

              // Order -> Store relationship
              modelBuilder.Entity<orders>()
                  .HasRequired(o => o.stores)
                  .WithMany(s => s.orders)
                  .HasForeignKey(o => o.store_id);

              // Order Items -> Order relationship
              modelBuilder.Entity<order_items>()
                  .HasRequired(oi => oi.orders)
                  .WithMany(o => o.order_items)
                  .HasForeignKey(oi => oi.order_id);

              // Order Items -> Product relationship
              modelBuilder.Entity<order_items>()
                  .HasRequired(oi => oi.products)
                  .WithMany(p => p.order_items)
                  .HasForeignKey(oi => oi.product_id);

              // Stocks -> Product relationship
              modelBuilder.Entity<stocks>()
                  .HasRequired(st => st.products)
                  .WithMany(p => p.stocks)
                  .HasForeignKey(st => st.product_id);

              // Stocks -> Store relationship
              modelBuilder.Entity<stocks>()
                  .HasRequired(st => st.stores)
                  .WithMany(s => s.stocks)
                  .HasForeignKey(st => st.store_id);
          }
        */
    }
}